" Misc configuration
set nocompatible
set hidden
set number
set showmatch
set matchtime=6
set encoding=utf-8
set history=1000
set timeoutlen=250
set expandtab
set smarttab
set shiftwidth=2
set tabstop=2
set smartindent
set autoindent
set wrap
set ruler
set nobackup
set nowritebackup
set noswapfile
set backspace=indent,eol,start
set incsearch
set termguicolors

let mapleader=","

" For minpac
set packpath^=~/.vim
packadd minpac

" Initialize minpac
call minpac#init()

" Let minpac manage minpac itself
call minpac#add('k-takata/minpac', {'type': 'start'}) "

" Plugins
call minpac#add('scrooloose/nerdtree')
call minpac#add('scrooloose/nerdcommenter')
call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-rake')
call minpac#add('tpope/vim-rails')
call minpac#add('dense-analysis/ale')
call minpac#add('godlygeek/tabular')
call minpac#add('ervandew/supertab')
call minpac#add('vim-ruby/vim-ruby')
call minpac#add('Raimondi/delimitMate')
call minpac#add('tpope/vim-endwise')
call minpac#add('mattn/emmet-vim')
call minpac#add('fatih/vim-go')
call minpac#add('catppuccin/vim')
call minpac#add('rking/ag.vim')
call minpac#add('vim-ctrlspace/vim-ctrlspace')
call minpac#add('vim-airline/vim-airline')

" Enable filetype (for minpac)
filetype plugin indent on

" NERDTree configuration
autocmd VimEnter * if !argc() | NERDTree | endif

" Colorscheme configuration
colorscheme catppuccin_frappe
syntax on


" Set airline theme
let g:airline_theme='catppuccin_frappe'

" Supertab configuration
let g:SuperTabDefaultCompletionType='<C-X><C-O>'

" Rubycomplete configuration
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
highlight Pmenu ctermbg=238 gui=bold

" Some keys mappings (save + save and exit)
noremap <Leader>s :w<CR>
inoremap <Leader>s <ESC>:w<CR>i
inoremap <Leader>se <ESC>:w<CR>

" Copy/Paste mappings
noremap <Leader>y :.w !pbcopy<CR><CR>
noremap <Leader>p :r !pbpaste<CR>
vmap <Leader>y :w !pbcopy<CR><CR>

" Zencoding mappings
let g:user_zen_expandabbr_key = '<Leader>x'
let g:use_zen_complete_tag = 1
let g:user_zen_emmet_mode = 'a'

" Use ag for searching through files
if executable("ag")
  let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""'
endif

" Save/Reload workspaces on exit/start
let g:CtrlSpaceLoadLastWorkspaceOnStart = 1
let g:CtrlSpaceSaveWorkspaceOnSwitch = 1
let g:CtrlSpaceSaveWorkspaceOnExit = 1
let g:CtrlSpaceUseMouseAndArrowsInTerm = 1

let g:CtrlSpaceFileEngine = ''

" Use higher search timing to ensure responsiveness
let g:CtrlSpaceSearchTiming = 500

" Specify file path formatter
let g:airline#extensions#tabline#formatter = 'unique_tail'

" Go mappings
autocmd FileType go nmap <Leader>r <Plug>(go-run)
