" Misc configuration
set hidden
set number
set showmatch
set matchtime=5
set encoding=utf-8
set history=1000
set timeoutlen=250
set expandtab
set smarttab
set shiftwidth=2
set tabstop=2
set smartindent
set autoindent
set wrap
set ruler
set nobackup
set nowritebackup
set noswapfile
set backspace=indent,eol,start
set incsearch

let mapleader=","

" Vundle specific configuration
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle.vim/
call vundle#rc()

" Let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Manage other bundles too
Plugin 'Lokaltog/vim-powerline'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround.git'
Plugin 'tpope/vim-rake.git'
Plugin 'tpope/vim-rails.git'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'kchmck/vim-coffee-script'
Plugin 'scrooloose/syntastic.git'
Plugin 'godlygeek/tabular.git'
Plugin 'ervandew/supertab'
Plugin 'vim-scripts/rubycomplete.vim'
Plugin 'xenoterracide/html.vim'
Plugin 'instant-markdown.vim'
Plugin 'delimitMate.vim'
Plugin 'tpope/vim-endwise.git'
Plugin 'nono/vim-handlebars.git'
Plugin 'mattn/emmet-vim.git'
Plugin 'dsawardekar/ember.vim'
Plugin 'honza/dockerfile.vim'
Plugin 'fatih/vim-go.git'
Plugin 'Shougo/neocomplcache'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'morhetz/gruvbox'
Plugin 'kien/ctrlp.vim'

" Enable filetype plugins                                                                                                                       
filetype plugin on                                                                                                                              
filetype indent on    

" NERDTree configuration
autocmd VimEnter * if !argc() | NERDTree | endif

" Colorscheme configuration
colorscheme gruvbox
set background=dark
syntax on 

" Powerline configuration
let g:Powerline_symbols='fancy'
let g:Powerline_colorscheme='zenburn'

" Supertab configuration
let g:SuperTabDefaultCompletionType='<C-X><C-O>'

" Rubycomplete configuration
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
highlight Pmenu ctermbg=238 gui=bold

" Some keys mappings 
noremap <Leader>s :w<CR>
inoremap <Leader>s <ESC>:w<CR>i
inoremap <Leader>se <ESC>:w<CR>

" Copy/Paste mappings
noremap <Leader>y :.w !pbcopy<CR><CR>
noremap <Leader>p :r !pbpaste<CR>
vmap <Leader>y :w !pbcopy<CR><CR>

" ctrpl mappings
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" Zencoding mappings
let g:user_zen_expandabbr_key = '<Leader>x'
let g:use_zen_complete_tag = 1
let g:user_zen_emmet_mode = 'a'

" Use neosnippet instead of utilsnips which is broken on older versions of
" python (it seems)
let g:go_snippet_engine = "neosnippet"

" Go mappings
autocmd FileType go nmap <Leader>r <Plug>(go-run)
