# bash_profile

declare -a files=(
  $HOME/.dotfiles/bash/bash_exports # Exports
  $HOME/.dotfiles/bash/bash_aliases # Aliases
  $HOME/.dotfiles/bash/gh.bash # Use gh to move around github/personal repos
  $HOME/.dotfiles/bash/completions/gh.bash
)

# If these files are readable, source them
for index in ${!files[*]}
do
  if [[ -r ${files[$index]} ]]; then
    source ${files[$index]}
  fi
done

unset files

# Use bash completion (install via homebrew)
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# Git completion
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# tmux
[ -n "$TMUX" ] && export TERM=screen-256color

# Always start ssh-agent
[ -z "$SSH_AUTH_SOCK" ] && eval "$(ssh-agent -s)"

# Load starship prompt
eval "$(starship init bash)"

# Load bash-preexec
[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh

# Load atuin
eval "$(atuin init bash)"

# Activate mise when a session is started
eval "$(mise activate bash)"

. "$HOME/.cargo/env"
