# bashrc

# Reload the profile whenever starting a new session.
[ -n "$PS1" ] && source ~/.bash_profile

PATH=$PATH:$GOBIN # Add RVM to PATH for scripting

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"