# bash_aliases

# Bundler aliases
alias bx='bundle exec'

# PostgreSQL aliases
alias pg='pg_ctl -D /usr/local/var/postgres/ -l /usr/local/var/postgres/server.log'

# Reload shell session
alias reload='source ~/.bash_profile'
