# bash_profile

declare -a files=(
  $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
  $HOME/.dotfiles/bash/bash_exports # Exports
  $HOME/.dotfiles/bash/bash_aliases # Aliases
  $HOME/.dotfiles/bash/bash_prompt # Prompt
  $HOME/documents/dev/github.com/ahazem/gh/bash/gh.bash # Use gh to move around github repos
  $HOME/documents/dev/github.com/ahazem/gh/completions/gh.bash
  #$HOME/.dotfiles/bash/bash_paths  # Path modifications
)

# If these files are readable, source them
for index in ${!files[*]}
do
  if [[ -r ${files[$index]} ]]; then
    source ${files[$index]}
  fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source bash completion path (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
  source $bash_completion_path
fi

# tmux
[ -n "$TMUX" ] && export TERM=screen-256color

# Add python to path (for awsudo)
export PATH="$(python -m site --user-base)/bin:${PATH}"

# Add elasticsearch home to path
export PATH="$ES_HOME/bin:${PATH}"
